# Build the verifyfulcio binary
FROM registry.access.redhat.com/ubi9/go-toolset@sha256:e91cbbd0b659498d029dd43e050c8a009c403146bfba22cbebca8bcd0ee7925f AS build-env
WORKDIR /ctlog-verifyfulcio
RUN git config --global --add safe.directory /ctlog-verifyfulcio

COPY . .
USER root

RUN make build-ctlog-verifyfulcio

# Install server
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:a50731d3397a4ee28583f1699842183d4d24fadcc565c4688487af9ee4e13a44

COPY --from=build-env /ctlog-verifyfulcio/verifyfulcio /usr/local/bin/verifyfulcio
RUN chown root:0 /usr/local/bin/verifyfulcio && chmod g+wx /usr/local/bin/verifyfulcio

#Configure home directory
ENV HOME=/home
RUN chgrp -R 0 /${HOME} && chmod -R g=u /${HOME}

WORKDIR ${HOME}

LABEL description="The job responsible for verifying Fulcio."
LABEL io.k8s.description="The job responsible for verifying Fulcio."
LABEL io.k8s.display-name="Fulcio verification job container image for Red Hat Trusted Artifact Signer."
LABEL io.openshift.tags="verifyfulcio, Red Hat trusted artifact signer."
LABEL summary="Provides the binary for verifyfulcio."

# Set the binary as the entrypoint of the container
ENTRYPOINT ["verifyfulcio"]
