# Build the managectroots binary
FROM registry.access.redhat.com/ubi9/go-toolset@sha256:a7d68b27e36edc6befe7dde94dd1db34c728a47df602998bd66c737d84813b5a AS build-env
WORKDIR /ctlog-managectroots
RUN git config --global --add safe.directory /ctlog-managectroots

COPY . .
USER root

RUN make build-ctlog-managectroots

# Install server
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:9c810eccada0cc6f25b46eeeea4516bab01828faef4fdd2fe49c760518b90dd1
COPY --from=build-env /ctlog-managectroots/managectroots /usr/local/bin/managectroots
RUN chown root:0 /usr/local/bin/managectroots && chmod g+wx /usr/local/bin/managectroots

#Configure home directory
ENV HOME=/home
RUN chgrp -R 0 /${HOME} && chmod -R g=u /${HOME}

WORKDIR ${HOME}

LABEL description="The job responsible for managing the roots of the CT (Certificate Transparency) server."
LABEL io.k8s.description="The job responsible for managing the roots of the CT (Certificate Transparency) server."
LABEL io.k8s.display-name="managectroots job container image for Red Hat Trusted Artifact Signer."
LABEL io.openshift.tags="managectroots, Red Hat trusted artifact signer."
LABEL summary="Provides the binary for the managectroots job."

# Set the binary as the entrypoint of the container
ENTRYPOINT ["managectroots"]
